/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fakeifood;
import db.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author danda
 */
public class FramePrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipalCliente
     */
    public FramePrincipalCliente() throws SQLException {
        initComponents();
        
        BuscaDados buscarRestaurantes = new BuscaDados();
        ResultSet rs = buscarRestaurantes.selectRestaurantes();
        
        while(rs.next()){
            ResultSet categoriaPrincipal = buscarRestaurantes.selectRestauranteCategorias(rs.getInt("id_restaurante"));
            pnlPreviewRest PR = new pnlPreviewRest(rs.getString("nome_restaurante"), categoriaPrincipal.getString("nome_categoria"), rs.getInt("entrega_rapida"));
            pnlExibicao.add(PR);
        }
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBasePrincipal = new javax.swing.JPanel();
        txtLogoMarca = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnIconEntregaRapida = new javax.swing.JButton();
        btnIconEntregaGratis = new javax.swing.JButton();
        btnIconPopular = new javax.swing.JButton();
        btnIconMaisPedidos = new javax.swing.JButton();
        btnIconPromocoes = new javax.swing.JButton();
        btnIconCategorias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlExibicao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlBasePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlBasePrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBasePrincipal.setMaximumSize(new java.awt.Dimension(918, 559));
        pnlBasePrincipal.setMinimumSize(new java.awt.Dimension(918, 559));
        pnlBasePrincipal.setPreferredSize(new java.awt.Dimension(918, 559));

        txtLogoMarca.setBackground(new java.awt.Color(255, 153, 102));
        txtLogoMarca.setFont(new java.awt.Font("Square721 Cn BT", 0, 36)); // NOI18N
        txtLogoMarca.setForeground(new java.awt.Color(255, 153, 102));
        txtLogoMarca.setText("Fake-Ifood");

        jTextField1.setText("Pesquise aqui! Digite nomes de restaurantes ou pratos");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnIconEntregaRapida.setText("Entrega rápida");
        btnIconEntregaRapida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconEntregaRapidaActionPerformed(evt);
            }
        });

        btnIconEntregaGratis.setText("Frete Grátis");
        btnIconEntregaGratis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconEntregaGratisActionPerformed(evt);
            }
        });

        btnIconPopular.setText("Restaurante popular");
        btnIconPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconPopularActionPerformed(evt);
            }
        });

        btnIconMaisPedidos.setText("Mais pedidos");
        btnIconMaisPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconMaisPedidosActionPerformed(evt);
            }
        });

        btnIconPromocoes.setText("Promoções");
        btnIconPromocoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconPromocoesActionPerformed(evt);
            }
        });

        btnIconCategorias.setText("Categorias");
        btnIconCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconCategoriasActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlExibicao.setBackground(new java.awt.Color(255, 255, 255));
        pnlExibicao.setLayout(new java.awt.GridLayout(0, 2, 8, 8));
        jScrollPane1.setViewportView(pnlExibicao);

        javax.swing.GroupLayout pnlBasePrincipalLayout = new javax.swing.GroupLayout(pnlBasePrincipal);
        pnlBasePrincipal.setLayout(pnlBasePrincipalLayout);
        pnlBasePrincipalLayout.setHorizontalGroup(
            pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasePrincipalLayout.createSequentialGroup()
                .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBasePrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLogoMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBasePrincipalLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIconPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIconEntregaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIconEntregaGratis, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIconPromocoes, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIconCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIconMaisPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 120, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlBasePrincipalLayout.setVerticalGroup(
            pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLogoMarca))
                .addGap(78, 78, 78)
                .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIconEntregaRapida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIconEntregaGratis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIconCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlBasePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIconPopular, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIconMaisPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIconPromocoes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlBasePrincipal, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIconCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconCategoriasActionPerformed

    private void btnIconPromocoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconPromocoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconPromocoesActionPerformed

    private void btnIconMaisPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconMaisPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconMaisPedidosActionPerformed

    private void btnIconPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconPopularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconPopularActionPerformed

    private void btnIconEntregaGratisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconEntregaGratisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconEntregaGratisActionPerformed

    private void btnIconEntregaRapidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconEntregaRapidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIconEntregaRapidaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FramePrincipalCliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FramePrincipalCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconCategorias;
    private javax.swing.JButton btnIconEntregaGratis;
    private javax.swing.JButton btnIconEntregaRapida;
    private javax.swing.JButton btnIconMaisPedidos;
    private javax.swing.JButton btnIconPopular;
    private javax.swing.JButton btnIconPromocoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlBasePrincipal;
    private javax.swing.JPanel pnlExibicao;
    private javax.swing.JLabel txtLogoMarca;
    // End of variables declaration//GEN-END:variables
}
