package fakeifood;
import db.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicial
     */
    public FrameInicial() {
        initComponents();
        btnGroup.add(btnCliente);
        btnGroup.add(btnRestaurante);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fldEmail = new javax.swing.JTextField();
        fldSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblFacaLogin = new javax.swing.JLabel();
        lblLogo1 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JRadioButton();
        btnRestaurante = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        fldEmail.setForeground(new java.awt.Color(255, 153, 153));
        fldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldEmail.setText("Digite seu e-mail");
        fldEmail.setToolTipText("Digite seu e-mail");
        fldEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldEmailActionPerformed(evt);
            }
        });

        fldSenha.setForeground(new java.awt.Color(255, 153, 153));
        fldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fldSenha.setToolTipText("");
        fldSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldSenhaActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblFacaLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFacaLogin.setText("Faça o login!");

        lblLogo1.setFont(new java.awt.Font("Square721 Cn BT", 0, 48)); // NOI18N
        lblLogo1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo1.setText("Fake-Ifood");

        btnCliente.setBackground(new java.awt.Color(255, 153, 102));
        btnCliente.setText("Cliente");
        btnCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnRestaurante.setBackground(new java.awt.Color(255, 153, 102));
        btnRestaurante.setText("Restaurante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFacaLogin)
                    .addComponent(lblLogo1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btnRestaurante)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblLogo1)
                .addGap(38, 38, 38)
                .addComponent(lblFacaLogin)
                .addGap(18, 18, 18)
                .addComponent(fldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(fldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnRestaurante))
                .addGap(11, 11, 11)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldEmailActionPerformed

    private void fldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        // TODO add your handling code here:
        
        String email = fldEmail.getText();
        char[] senhaChar = fldSenha.getPassword();
        String senhaString = "";
        
        // transformando senha pega pelo FLD em uma string 
        for(int i = 0; i< senhaChar.length; i++){
            senhaString = senhaString + senhaChar[i];
        }
        
        BuscaDados login = new BuscaDados();

        ResultSet rs;
        try {
            if(btnCliente.isSelected()){
                rs = login.selectClienteExiste(email, senhaString);
                if(rs.next()){
                // encontrou esse cliente no banco de dados
                    FramePrincipalCliente teste = new FramePrincipalCliente();
                    teste.setVisible(true);
                    dispose();
                }else{
                // não encontrou esse cliente no banco de dados
                    JOptionPane.showMessageDialog(null, "naoteve");
                }
            }else if(btnRestaurante.isSelected()){
                rs = login.selectRestauranteExiste(email, senhaString);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "teve");
                }else{
                    JOptionPane.showMessageDialog(null, "naoteve");
                }
            }else
                JOptionPane.showMessageDialog(null, "Selecione uma das categorias.");

        } catch (SQLException ex) {
            Logger.getLogger(FrameInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCliente;
    private javax.swing.JButton btnEntrar;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JRadioButton btnRestaurante;
    private javax.swing.JTextField fldEmail;
    private javax.swing.JPasswordField fldSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFacaLogin;
    private javax.swing.JLabel lblLogo1;
    // End of variables declaration//GEN-END:variables
}
